version: '3'
services:
  app:
    image: node:20-slim
    container_name: bk-app
    ports:
      - 3000:3000
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - api
      - solr
  
  fuseki:
    build: ./fuseki
    container_name: bk-fuseki
    ports:
      - 3030:3030
    volumes:
      - ./fuseki/database:/fuseki/database
    # command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - bk-network

  mariadb:
    image: mariadb:11
    container_name: bk-mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: bkpass
      MYSQL_DATABASE: bk
      MYSQL_USER: admin
      MYSQL_PASSWORD: bkpass
    volumes:
      - ./db:/var/lib/mysql
    # restart: always
    expose:
      - 3306
    networks:
      - bk-network
      # - 33060

  solr:
    image: solr:9.3-slim
    container_name: bk-solr
    user: solr
    ports:
      - 8983:8983
    volumes:
      # - ./solr/data:/var/solr/data
      - ./solr/configsets/authority:/var/solr/data/configsets/authority
    networks:
      - solr_network

  api:
    build: ./api
    container_name: bk-api
    ports:
      - "8000:8000"
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - mariadb
      - solr
      - fuseki
    links:
      - mariadb
      - solr
      - fuseki
    environment:
      DB_HOST: mariadb
      DB_USER: admin
      DB_PASSWORD: bkpass
      DB_NAME: bk
    networks:
      - bk-network
    
networks:
  bk-network:
  solr_network:
    driver: bridge



